import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class timezoneService {
  
    timezones =  [
        { value: 'Buenos_Aires', viewValue: 'America/Argentina/Buenos_Aires'},
        { value: 'Cordoba', viewValue: 'America/Argentina/Cordoba'},
        { value: 'Salta', viewValue: 'America/Argentina/Salta'},
        { value: 'Jujuy', viewValue: 'America/Argentina/Jujuy'},
        { value: 'Tucuman', viewValue: 'America/Argentina/Tucuman'},
        { value: 'Catamarca', viewValue: 'America/Argentina/Catamarca'},
        { value: 'La_Rioja', viewValue: 'America/Argentina/La_Rioja'},
        { value: 'San_Juan', viewValue: 'America/Argentina/San_Juan'},
        { value: 'Mendoza', viewValue: 'America/Argentina/Mendoza'},
        { value: 'San_Luis', viewValue: 'America/Argentina/San_Luis'},
        { value: 'Rio_Gallegos', viewValue: 'America/Argentina/Rio_Gallegos'},
        { value: 'Ushuaia', viewValue: 'America/Argentina/Ushuaia'},
        { value: 'Barbados', viewValue: 'America/Barbados'},
        { value: 'La_Paz', viewValue: 'America/La_Paz'},
        { value: 'Belem', viewValue: 'America/Belem'},
        { value: 'Fortaleza', viewValue: 'America/Fortaleza'},
        { value: 'Recife', viewValue: 'America/Recife'},
        { value: 'Araguaina', viewValue: 'America/Araguaina'},
        { value: 'Maceio', viewValue: 'America/Maceio'},
        { value: 'Bahia', viewValue: 'America/Bahia'},
        { value: 'Sao_Paulo', viewValue: 'America/Sao_Paulo'},
        { value: 'Campo_Grande', viewValue: 'America/Campo_Grande'},
        { value: 'Cuiaba', viewValue: 'America/Cuiaba'},
        { value: 'Porto_Velho', viewValue: 'America/Porto_Velho'},
        { value: 'Boa_Vista', viewValue: 'America/Boa_Vista'},
        { value: 'Manaus', viewValue: 'America/Manaus'},
        { value: 'Eirunepe', viewValue: 'America/Eirunepe'},
        { value: 'Rio_Branco', viewValue: 'America/Rio_Branco'},
        { value: 'Nassau', viewValue: 'America/Nassau'},
        { value: 'Belize', viewValue: 'America/Belize'},
        { value: 'St_Johns', viewValue: 'America/St_Johns'},
        { value: 'Halifax', viewValue: 'America/Halifax'},
        { value: 'Glace_Bay', viewValue: 'America/Glace_Bay'},
        { value: 'Moncton', viewValue: 'America/Moncton'},
        { value: 'Goose_Bay', viewValue: 'America/Goose_Bay'},
        { value: 'Blanc-Sablon', viewValue: 'America/Blanc-Sablon'},
        { value: 'Toronto', viewValue: 'America/Toronto'},
        { value: 'Nipigon', viewValue: 'America/Nipigon'},
        { value: 'Thunder_Bay', viewValue: 'America/Thunder_Bay'},
        { value: 'Iqaluit', viewValue: 'America/Iqaluit'},
        { value: 'Pangnirtung', viewValue: 'America/Pangnirtung'},
        { value: 'Atikokan', viewValue: 'America/Atikokan'},
        { value: 'Winnipeg', viewValue: 'America/Winnipeg'},
        { value: 'Rainy_River', viewValue: 'America/Rainy_River'},
        { value: 'Resolute', viewValue: 'America/Resolute'},
        { value: 'Rankin_Inlet', viewValue: 'America/Rankin_Inlet'},
        { value: 'Regina', viewValue: 'America/Regina'},
        { value: 'Swift_Current', viewValue: 'America/Swift_Current'},
        { value: 'Edmonton', viewValue: 'America/Edmonton'},
        { value: 'Cambridge_Bay', viewValue: 'America/Cambridge_Bay'},
        { value: 'Yellowknife', viewValue: 'America/Yellowknife'},
        { value: 'Inuvik', viewValue: 'America/Inuvik'},
        { value: 'Creston', viewValue: 'America/Creston'},
        { value: 'Dawson_Creek', viewValue: 'America/Dawson_Creek'},
        { value: 'Fort_Nelson', viewValue: 'America/Fort_Nelson'},
        { value: 'Vancouver', viewValue: 'America/Vancouver'},
        { value: 'Whitehorse', viewValue: 'America/Whitehorse'},
        { value: 'Dawson', viewValue: 'America/Dawson'},
        { value: 'Santiago', viewValue: 'America/Santiago'},
        { value: 'Punta_Arenas', viewValue: 'America/Punta_Arenas'},
        { value: 'Bogota', viewValue: 'America/Bogota'},
        { value: 'Costa_Rica', viewValue: 'America/Costa_Rica'},
        { value: 'Havana', viewValue: 'America/Havana'},
        { value: 'Curacao', viewValue: 'America/Curacao'},
        { value: 'Santo_Domingo', viewValue: 'America/Santo_Domingo'},
        { value: 'Guayaquil', viewValue: 'America/Guayaquil'},
        { value: 'Cayenne', viewValue: 'America/Cayenne'},
        { value: 'Godthab', viewValue: 'America/Godthab'},
        { value: 'Danmarkshavn', viewValue: 'America/Danmarkshavn'},
        { value: 'Scoresbysund', viewValue: 'America/Scoresbysund'},
        { value: 'Cayenne', viewValue: 'America/Cayenne'},
        { value: 'Godthab', viewValue: 'America/Godthab'},
        { value: 'Danmarkshavn', viewValue: 'America/Danmarkshavn'},
        { value: 'Scoresbysund', viewValue: 'America/Scoresbysund'},
        { value: 'Thule', viewValue: 'America/Thule'},
        { value: 'Guatemala', viewValue: 'America/Guatemala'},
        { value: 'Guyana', viewValue: 'America/Guyana'},
        { value: 'Tegucigalpa', viewValue: 'America/Tegucigalpa'},
        { value: 'Port-au-Prince', viewValue: 'America/Port-au-Prince'},
        { value: 'Jamaica', viewValue: 'America/Jamaica'},
        { value: 'Martinique', viewValue: 'America/Martinique'},
        { value: 'Mexico_City', viewValue: 'America/Mexico_City'},
        { value: 'Cancun', viewValue: 'America/Cancun'},
        { value: 'Merida', viewValue: 'America/Merida'},
        { value: 'Monterrey', viewValue: 'America/Monterrey'},
        { value: 'Matamoros', viewValue: 'America/Matamoros'},
        { value: 'Caracas', viewValue: 'America/Caracas'},
        { value: 'Mazatlan', viewValue: 'America/Mazatlan'},
        { value: 'Chihuahua', viewValue: 'America/Chihuahua'},
        { value: 'Ojinaga', viewValue: 'America/Ojinaga'},
        { value: 'Hermosillo', viewValue: 'America/Hermosillo'},
        { value: 'Tijuana', viewValue: 'America/Tijuana'},
        { value: 'Bahia_Banderas', viewValue: 'America/Bahia_Banderas'},
        { value: 'Managua', viewValue: 'America/Managua'},
        { value: 'Panama', viewValue: 'America/Panama'},
        { value: 'Lima', viewValue: 'America/Lima'},
        { value: 'Miquelon', viewValue: 'America/Miquelon'},
        { value: 'Puerto_Rico', viewValue: 'America/Puerto_Rico'},
        { value: 'El_Salvador', viewValue: 'America/El_Salvador'},
        { value: 'Grand_Turk', viewValue: 'America/Grand_Turk'},
        { value: 'Paramaribo', viewValue: 'America/Paramaribo'},
        { value: 'Asuncion', viewValue: 'America/Asuncion'},
        { value: 'Port_of_Spain', viewValue: 'America/Port_of_Spain'},
        { value: 'New_York', viewValue: 'America/New_York'},
        { value: 'Detroit', viewValue: 'America/Detroit'},
        { value: 'Louisville', viewValue: 'America/Kentucky/Louisville'},
        { value: 'Monticello', viewValue: 'America/Kentucky/Monticello'},
        { value: 'Indianapolis', viewValue: 'America/Indiana/Indianapolis'},
        { value: 'Vincennes', viewValue: 'America/Indiana/Vincennes'},
        { value: 'Winamac', viewValue: 'America/Indiana/Winamac'},
        { value: 'Marengo', viewValue: 'America/Indiana/Marengo'},
        { value: 'Petersburg', viewValue: 'America/Indiana/Petersburg'},
        { value: 'Vevay', viewValue: 'America/Indiana/Vevay'},
        { value: 'Tell_City', viewValue: 'America/Indiana/Tell_City'},
        { value: 'Knox', viewValue: 'America/Indiana/Knox'},
        { value: 'Chicago', viewValue: 'America/Chicago'},
        { value: 'Menominee', viewValue: 'America/Menominee'},
        { value: 'Denver', viewValue: 'America/Denver'},
        { value: 'Boise', viewValue: 'America/Boise'},
        { value: 'Phoenix', viewValue: 'America/Phoenix'},
        { value: 'Center', viewValue: 'America/North_Dakota/Center'},
        { value: 'New_Salem', viewValue: 'America/North_Dakota/New_Salem'},
        { value: 'Beulah', viewValue: 'America/North_Dakota/Beulah'},
        { value: 'Los_Angeles', viewValue: 'America/Los_Angeles'},
        { value: 'Anchorage', viewValue: 'America/Anchorage'},
        { value: 'Juneau', viewValue: 'America/Juneau'},
        { value: 'Sitka', viewValue: 'America/Sitka'},
        { value: 'Metlakatla', viewValue: 'America/Metlakatla'},
        { value: 'Yakutat', viewValue: 'America/Yakutat'},
        { value: 'Nome', viewValue: 'America/Nome'},
        { value: 'Adak', viewValue: 'America/Adak'},
        { value: 'Montevideo', viewValue: 'America/Montevideo'},
      ]
  constructor(){}

 

}